version: '3.4'

# ---------------------------------------------------------
# Network Configuration
# ---------------------------------------------------------
networks:
  main:
    ipam:
      config:
        - subnet: 172.40.1.0/24

# *************************************************************
# Services Configuration
# *************************************************************
services:
  # ------------------------
  # Redis
  # ------------------------
  redis:
    image: redis:5.0
    restart: on-failure
    networks:
      main:
        ipv4_address: 172.40.1.4
    command: ["sh", "-c", "exec redis-server --requirepass \"${REDIS_PASSWORD}\""]
